//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.28 at 03:46:13 AM ICT 
//


package com.flightbooking.flight_booking_soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.flightbooking.flight_booking_soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.flightbooking.flight_booking_soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PostPromoRequest }
     * 
     */
    public PostPromoRequest createPostPromoRequest() {
        return new PostPromoRequest();
    }

    /**
     * Create an instance of {@link PromoData }
     * 
     */
    public PromoData createPromoData() {
        return new PromoData();
    }

    /**
     * Create an instance of {@link PostCancelBookingResponse }
     * 
     */
    public PostCancelBookingResponse createPostCancelBookingResponse() {
        return new PostCancelBookingResponse();
    }

    /**
     * Create an instance of {@link PostBookingRequest }
     * 
     */
    public PostBookingRequest createPostBookingRequest() {
        return new PostBookingRequest();
    }

    /**
     * Create an instance of {@link BookingData }
     * 
     */
    public BookingData createBookingData() {
        return new BookingData();
    }

    /**
     * Create an instance of {@link PostPromoResponse }
     * 
     */
    public PostPromoResponse createPostPromoResponse() {
        return new PostPromoResponse();
    }

    /**
     * Create an instance of {@link PostCancelBookingRequest }
     * 
     */
    public PostCancelBookingRequest createPostCancelBookingRequest() {
        return new PostCancelBookingRequest();
    }

    /**
     * Create an instance of {@link PostBookingResponse }
     * 
     */
    public PostBookingResponse createPostBookingResponse() {
        return new PostBookingResponse();
    }

}
