//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.28 at 03:46:13 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://flightbooking.com/flight-booking-soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.flightbooking.flight_booking_soap;
