//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.28 at 03:46:13 AM ICT 
//


package com.flightbooking.flight_booking_soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bookingData" type="{http://flightbooking.com/flight-booking-soap}bookingData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bookingData"
})
@XmlRootElement(name = "postBookingRequest")
public class PostBookingRequest {

    @XmlElement(required = true)
    protected BookingData bookingData;

    /**
     * Gets the value of the bookingData property.
     * 
     * @return
     *     possible object is
     *     {@link BookingData }
     *     
     */
    public BookingData getBookingData() {
        return bookingData;
    }

    /**
     * Sets the value of the bookingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingData }
     *     
     */
    public void setBookingData(BookingData value) {
        this.bookingData = value;
    }

}
